#!/bin/bash

OLD_CFG_PATH="/usr/etc/coderu/coderu.cfg"
NEW_CFG_PATH=tmp$OLD_CFG_PATH

#OLD_CFG_PATH="old.cfg"
#NEW_CFG_PATH="new.cfg"

[ -f $OLD_CFG_PATH ] || exit 0

echo "Merging old and new configuration files..."

dpkg-deb --extract coderu.deb tmp

arrayIndex=0

regex='([^=]*)=([^#]*)( .*)?'

while read line
do
    if [[ "$line" =~ $regex ]]
    then
        OLD_SETTINGS[$arrayIndex]=${BASH_REMATCH[1]}
        OLD_VALUES[$arrayIndex]=${BASH_REMATCH[2]}
        #echo "${BASH_REMATCH[1]}=${BASH_REMATCH[2]}"
        arrayIndex=$[$arrayIndex+1]
    fi
done < $OLD_CFG_PATH

rm $OLD_CFG_PATH
touch $OLD_CFG_PATH

oldSettingsCount=${#OLD_SETTINGS[*]}
while read line
do
    if [[ "$line" =~ $regex ]]
    then
        setting=${BASH_REMATCH[1]}
        value=${BASH_REMATCH[2]}
        
        oldSettingsIndex=0
        while [[ $oldSettingsIndex -lt $oldSettingsCount ]]
        do
            #echo "   $setting == ${OLD_SETTINGS[$oldSettingsIndex]}"
            if [ "$setting" == "${OLD_SETTINGS[$oldSettingsIndex]}" ]
            then
                #echo "$line/\"$value\"/${OLD_VALUES[$oldSettingsIndex]}"
                line=${line/"$value"/${OLD_VALUES[$oldSettingsIndex]}}
                break
            fi
            let oldSettingsIndex++
        done
    fi
    echo "$line" >> $OLD_CFG_PATH
done < $NEW_CFG_PATH

rm -R tmp

echo "Merging successful!"
